USE SimpleBistroTest;

-- Try a different syntax for adding AUTO_INCREMENT
ALTER TABLE `Order` CHANGE OrderID OrderID INT AUTO_INCREMENT;
ALTER TABLE `Order` AUTO_INCREMENT = 4;

ALTER TABLE OrderItem CHANGE OrderItemID OrderItemID INT AUTO_INCREMENT;
ALTER TABLE OrderItem AUTO_INCREMENT = 5;

ALTER TABLE Payment CHANGE PaymentID PaymentID INT AUTO_INCREMENT;
ALTER TABLE Payment AUTO_INCREMENT = 4;

-- Verify
SHOW CREATE TABLE `Order`;
SHOW TABLE STATUS LIKE 'Order';